/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:459978bd-9e62-4153-adab-6480da884526",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9OmI1qJSM",
    "aws_user_pools_web_client_id": "7ue7h96035rj9f5pbaa61qc3k8",
    "oauth": {
        "domain": "1pagaquifb94f827-fb94f827-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://api.1pagaqui.com/",
        "redirectSignOut": "https://api.1pagaqui.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
